### PR TITLE
feat: Add supergfxctl-plasmoid

### PR DESCRIPTION
**Pull request by EyeCantCU**
The supergfxctl plasmoid allows users to adjust supergfxctl settings directly from the Plasma panel

Resolves: https://github.com/ublue-os/nvidia/issues/99

### CODE REVIEW

**Comment by EyeCantCU** [comment]
I had considered including this upstream, but it directly depends on supergfxctl making that impossible

**Review by EyeCantCU — COMMENTED** [review]
Everything should be good now. Made some mistakes in the spec file earlier that I addressed

**Comment by castrojo** [comment]
Does this end up on all the images or just kinoite?

**Comment by EyeCantCU** [comment]
All images unfortunately. I can look into how to include it for just Kinoite though

**Review by castrojo — APPROVED** [review]

**Pull request merged**
