### PR TITLE
feat(Silverblue): Add supergfxctl-gex GNOME Shell extension

### PR DESCRIPTION
**Pull request by EyeCantCU**
Adds the supergfxctl-gex extension to Silverblue images for managing multi-GPU Nvidia systems

### CODE REVIEW

**Comment by bsherman** [comment]
@EyeCantCU I'm curious from where this package is installed?

**Comment by EyeCantCU** [comment]
> @EyeCantCU I'm curious from where (which repo) this package is installed?

@bsherman it's built out of a COPR I setup for supergfxctl after the one we had been using dropped support for Fedora 37

https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/

**Comment by bsherman** [comment]
> @bsherman it's built out of a COPR I setup for supergfxctl after the one we had been using dropped support for Fedora 37
> 
> https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/

Good to know thank you. I was asking because I had thought we were working towards building any custom things like this in https://copr.fedorainfracloud.org/coprs/ublue-os/

Maybe this is where the perms management gets tricky, as perms are managed per project not at the "ublue-os" level.

**Comment by bsherman** [comment]
I'm fine approving this as is, just want to make sure we capture the goal if keeping these COPRs community maintainable and not locked to a single individual.

**Review by bsherman — APPROVED** [review]

**Comment by EyeCantCU** [comment]
As it is, we build what's submitted directly to COPR for both supergfxctl and supergfxctl-plasmoid. For Supergfxctl-gex, that's on GitLab so I would need to setup CI for that there (as far as I know). I do agree these should be under the Ublue domain and originally had asked for that when I was fixing the issue.

**Pull request merged**
