### PR TITLE
feat: switch to akmods repo provided nvidia kmod

### PR DESCRIPTION
**Pull request by bsherman**
This removes the akmod build process for nvidia drivers and the build of ublue-os-nvidia-addons from this repo, and instead installs said RPMs which are now built in the ublue-os/akmods repo.

Depends on https://github.com/ublue-os/akmods/pull/53

### CODE REVIEW

**Comment by bsherman** [comment]
Leaving as a draft until akmods is built and this can test.

**Comment by bsherman** [comment]
Ok, at this point, I've tested this by building the `silverblue-nvidia` image locally, using the already published to ghcr `akmods` repo containing nvidia 535 kmod, and then pushing the image to a LAN local container registry and rebooting.

Seems to be working pretty well!

Note: we need to update the website repo docs to reflect these changes as the README contents for this repo have been migrated there.

**Comment by bsherman** [comment]
I'm not sure why the "Build akmods package" checks are expected, but they can be ignored. I'm hoping they clear after this is merged and a clean build occurs there.

**Review by akdev1l — APPROVED** [review]

**Comment by bsherman** [comment]
Marked as draft as @akdev1l and I are discussing some improvements to [akmods](https://github.com/ublue-os/akmods) which may be helpful before merging this.

**Comment by bsherman** [comment]
Updated: now depends on https://github.com/ublue-os/akmods/pull/54

**Review by EyeCantCU — APPROVED** [review]

**Pull request merged**
