### PR TITLE
chore: bump driver version from 545 to 550

### PR DESCRIPTION
**Pull request by dylanmtaylor**

### CODE REVIEW

**Review by KyleGospo — APPROVED** [review]

**Review by bsherman — CHANGES_REQUESTED** [review]
Adding a request for changes simply to block merge until we have upstream akmods building cleanly with this.

Also a note: rpmfusion usually removes the previous "current" very quickly after publishing the new one. So in reality, we'll probably need to replace 545 with 550, rather than only add 550.

**Comment by dylanmtaylor** [comment]
> Adding a request for changes simply to block merge until we have upstream akmods building cleanly with this.
> 
> Also a note: rpmfusion usually removes the previous "current" very quickly after publishing the new one. So in reality, we'll probably need to replace 545 with 550, rather than only add 550.

This makes sense. I wouldn't merge something that doesn't build. I'll update it to swap 545 -> 550 when it's published.

**Comment by bsherman** [comment]
>  I wouldn't merge something that doesn't build. 

I didn't mean to imply you would, but crazier things have happened in this project. :-)

**Review by bsherman — APPROVED** [review]
Changes look good.

**Review by p5 — APPROVED** [review]

**Pull request merged**
